package com.findly.api.common.enums;

public enum AdminAuditAction {
    USER_STATUS_UPDATED,
    REPORT_STATUS_UPDATED,
    REPORT_VERIFICATION_UPDATED,
    CLAIM_STATUS_UPDATED,
    NOTIFICATION_DELETED,

    CONTACT_REQUEST_STATUS_UPDATED,

    CATEGORY_CONFIG_CREATED,
    CATEGORY_CONFIG_UPDATED,
    CATEGORY_CONFIG_DELETED
}